apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kafka-lab-keyvault
spec:
  provider: azure

  secretObjects:
    - secretName: kafka-lab-secrets
      type: Opaque
      data:
        - objectName: eventhubs-connection-string
          key: eventhubs-connection-string
        - objectName: sqlserver-connection-string
          key: sqlserver-connection-string

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"

    userAssignedIdentityID: "4bba247e-4287-4237-8fd9-63c9ff98f0af"

    keyvaultName: "kafka-lab-kv-prd"
    cloudName: ""

    objects: |
      array:
        - |
          objectName: eventhubs-connection-string
          objectType: secret
          objectVersion: ""
        - |
          objectName: sqlserver-connection-string
          objectType: secret
          objectVersion: ""

    tenantId: "e09c5a68-986b-433a-bee4-2f6b866246e9"